name: Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pdflatex
        run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra
      - name: Build pdf
        run: make upcgm
      - uses: actions/checkout@main
      - name: Compile and Deploy
        uses: jonhue/pubtex-action@main
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
